### PR TITLE
A number of somewhat dirty fixes

### PR DESCRIPTION
**Pull request by ENCRYPTEDFOREVER**

### CODE REVIEW

**Comment by kravetsone** [comment]
Uh thanks!

**Review by ark0f — APPROVED** [review]
If we take into account project's codebase then fixes are barely dirty. Thank you very much for PR!

**Comment by ENCRYPTEDFOREVER** [comment]
> If we take into account project's codebase then fixes are barely dirty. Thank you very much for PR!

Btw I'd appreciate some explanation on how your parser-matcher works, I didn't have courage to figure it out myself 😅

**Comment by ark0f** [comment]
> I'd appreciate some explanation on how your parser-matcher works

Write to the email from my GitHub profile, please. I can also give you access to the repo if you want

**Pull request merged**
